Add who to follow widget
OsgoodPaekid/React-project pull request #34
Opened 2023-11-12 17:03 UTC by OsgoodPaekid

closes #33

2023-12-02 19:50 UTC, alphaofficial requested changes
left some comments

2023-12-04 23:00 UTC, OsgoodPaekid commented on src/app/layout.js
> +import { WhoToFollow } from "./follow/page";
resolved

2023-12-04 23:01 UTC, OsgoodPaekid commented on src/app/follow/page.js
> +export async function WhoToFollow() {
resolved

2024-05-07 13:09 UTC, alphaofficial approved these changes

2024-05-07 13:11 UTC, merged